#!/usr/bin/env python3
"""Generate an ICS calendar file from a JSON events specification.

Input: JSON via stdin or --input FILE
Output: .ics file written to --output (default: syllabus_calendar.ics)

Each event in the JSON array supports these fields:
  summary      (str, required)  - Event title
  start        (str, required)  - ISO datetime or date: "2026-08-24T12:00:00" or "2026-09-25"
  end          (str, optional)  - ISO datetime/date; defaults to start + duration
  duration     (int, optional)  - Minutes; default 150 (2.5h). Ignored if end is set.
  location     (str, optional)  - Venue
  description  (str, optional)  - Notes
  rrule        (str, optional)  - RFC 5545 recurrence rule, e.g. "FREQ=WEEKLY;COUNT=7;BYDAY=MO,WE"
  exdate       (list, optional) - List of ISO datetime strings to exclude from recurrence
  alarm        (int, optional)  - Minutes before event to trigger alarm; default None (no alarm)
  all_day      (bool, optional) - True for date-only events (no time); default False
  category     (str, optional)  - For color-coding: "lecture"/"exam"/"deadline"/"holiday"/"other"

Timezone note:
  All datetimes are treated as local time in the user's timezone (default: Asia/Shanghai).
  The --timezone flag overrides this. ICS output uses VTIMEZONE for correct cross-platform import.

Apple Calendar / Outlook compatibility:
  ICS files generated by this script are compatible with Apple Calendar (macOS/iOS),
  Microsoft Outlook, Google Calendar, and any ICS-compliant calendar application.
  Simply double-click the .ics file to import.

Example JSON:
[
  {"summary": "COMPSCI 308 Lecture", "start": "2026-08-24T12:00:00",
   "location": "TBA", "rrule": "FREQ=WEEKLY;COUNT=7;BYDAY=MO,WE", "category": "lecture"},
  {"summary": "Midterm Exam", "start": "2026-09-16T12:00:00", "duration": 150,
   "location": "TBA", "category": "exam", "alarm": 1440, "description": "Covers Weeks 1-4"},
  {"summary": "Mid-Autumn Festival (No Class)", "start": "2026-09-25", "end": "2026-09-27",
   "all_day": true, "category": "holiday"}
]
"""

import json
import sys
import argparse
from datetime import datetime, timedelta
from textwrap import dedent


def escape_ics_text(text: str) -> str:
    """Escape special characters for ICS TEXT values and fold long lines."""
    text = text.replace("\\", "\\\\")
    text = text.replace(";", "\\;")
    text = text.replace(",", "\\,")
    text = text.replace("\n", "\\n")
    return text


def fold_line(line: str) -> str:
    """Fold long ICS lines per RFC 5545 (max 75 octets per line)."""
    if len(line.encode("utf-8")) <= 75:
        return line
    result = []
    while len(line.encode("utf-8")) > 75:
        split_at = 75
        while split_at > 0:
            candidate = line[:split_at]
            if len(candidate.encode("utf-8")) <= 75:
                break
            split_at -= 1
        result.append(line[:split_at])
        line = " " + line[split_at:]
    result.append(line)
    return "\r\n".join(result)


TIMEZONE = "Asia/Shanghai"

# VTIMEZONE definition for Asia/Shanghai (China Standard Time, UTC+8, no DST)
VTIMEZONE_CST = dedent("""\
BEGIN:VTIMEZONE
TZID:Asia/Shanghai
BEGIN:STANDARD
DTSTART:19700101T000000
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
TZNAME:CST
END:STANDARD
END:VTIMEZONE""")


def format_dt_local(dt_str: str) -> str:
    """Convert ISO datetime string to ICS local-time format: YYYYMMDDTHHMMSS"""
    dt = datetime.fromisoformat(dt_str)
    return dt.strftime("%Y%m%dT%H%M%S")


def format_date(dt_str: str) -> str:
    """Convert ISO date/datetime string to ICS DATE format: YYYYMMDD"""
    if "T" in dt_str:
        dt = datetime.fromisoformat(dt_str)
    else:
        dt = datetime.strptime(dt_str, "%Y-%m-%d")
    return dt.strftime("%Y%m%d")


def generate_ics(events, timezone=TIMEZONE, prodid="-//WorkBuddy//Syllabus Reader//EN"):
    """Generate a complete ICS calendar string from a list of event dicts."""
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        f"PRODID:{prodid}",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        "X-WR-CALNAME:Course Schedule",
    ]

    # Include VTIMEZONE for proper timezone handling in Outlook/Apple Calendar
    for l in VTIMEZONE_CST.strip().split('\n'):
        lines.append(l)

    for i, ev in enumerate(events):
        summary = ev.get("summary", "Untitled Event")
        start = ev["start"]
        all_day = ev.get("all_day", False)

        lines.append("BEGIN:VEVENT")
        lines.append(f"UID:workbuddy-syllabus-{i}-{int(datetime.now().timestamp())}")

        if all_day:
            start_date = format_date(start)
            end_date = format_date(ev.get("end", start))
            lines.append(f"DTSTART;VALUE=DATE:{start_date}")
            lines.append(f"DTEND;VALUE=DATE:{end_date}")
        else:
            start_formatted = format_dt_local(start)
            lines.append(f"DTSTART;TZID={timezone}:{start_formatted}")

            if "end" in ev:
                end_formatted = format_dt_local(ev["end"])
                lines.append(f"DTEND;TZID={timezone}:{end_formatted}")
            else:
                duration_min = ev.get("duration", 150)
                end_dt = datetime.fromisoformat(start) + timedelta(minutes=duration_min)
                end_formatted = end_dt.strftime("%Y%m%dT%H%M%S")
                lines.append(f"DTEND;TZID={timezone}:{end_formatted}")

        lines.append(f"SUMMARY:{escape_ics_text(summary)}")

        if ev.get("location"):
            lines.append(f"LOCATION:{escape_ics_text(ev['location'])}")

        desc_parts = []
        if ev.get("description"):
            desc_parts.append(ev["description"])
        if ev.get("category"):
            desc_parts.append(f"[Category: {ev['category']}]")
        if desc_parts:
            lines.append(f"DESCRIPTION:{escape_ics_text(' | '.join(desc_parts))}")

        if ev.get("category"):
            lines.append(f"CATEGORIES:{escape_ics_text(ev['category'])}")

        if ev.get("rrule"):
            lines.append(f"RRULE:{ev['rrule']}")

        if ev.get("exdate"):
            for ex in ev["exdate"]:
                ex_formatted = format_dt_local(ex)
                lines.append(f"EXDATE;TZID={timezone}:{ex_formatted}")

        if ev.get("alarm"):
            alarm_min = ev["alarm"]
            lines.append("BEGIN:VALARM")
            lines.append("ACTION:DISPLAY")
            lines.append(f"DESCRIPTION:Reminder: {escape_ics_text(summary)}")
            lines.append(f"TRIGGER:-PT{abs(alarm_min)}M")
            lines.append("END:VALARM")

        lines.append("END:VEVENT")

    lines.append("END:VCALENDAR")

    # Fold lines and join with CRLF per RFC 5545
    folded = []
    for line in lines:
        folded.append(fold_line(line))
    return "\r\n".join(folded) + "\r\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate an ICS calendar file from syllabus event data."
    )
    parser.add_argument(
        "--input", "-i",
        help="Path to JSON file containing events array. If omitted, reads from stdin."
    )
    parser.add_argument(
        "--output", "-o",
        default="syllabus_calendar.ics",
        help="Output .ics file path (default: syllabus_calendar.ics)"
    )
    parser.add_argument(
        "--timezone", "-t",
        default=TIMEZONE,
        help="Timezone for event times (default: Asia/Shanghai)"
    )
    parser.add_argument(
        "--prodid",
        default="-//WorkBuddy//Syllabus Reader//EN",
        help="PRODID string for the calendar (default: WorkBuddy)"
    )
    args = parser.parse_args()

    if args.input:
        with open(args.input, "r", encoding="utf-8") as f:
            events = json.load(f)
    else:
        raw = sys.stdin.read()
        events = json.loads(raw)

    if not isinstance(events, list):
        print("Error: Input must be a JSON array of events.", file=sys.stderr)
        sys.exit(1)

    ics_content = generate_ics(events, timezone=args.timezone, prodid=args.prodid)

    with open(args.output, "w", encoding="utf-8", newline="") as f:
        f.write(ics_content)

    print(f"Generated {args.output} with {len(events)} event(s).")


if __name__ == "__main__":
    main()
